### ISSUE TITLE
Update dependency to zeromq.js

### ISSUE THREAD

**Issue by henryoliver** [matrix-io/matrix-os#116]
Please, update the `zmq` dependency to the new `zeromq`.
http://zeromq.github.io/zeromq.js/
https://github.com/zeromq/zeromq.js

Thanks!

**Comment by diegoribero** [comment]
Hi @henryoliver, we are already using `zeromq`

https://github.com/matrix-io/matrix-os/blob/22211c581c332ecfd7ebc31a23d48e782f6fbca1/lib/service/zeromq.js#L5

https://github.com/matrix-io/matrix-os/blob/22211c581c332ecfd7ebc31a23d48e782f6fbca1/package.json#L72

**Comment by henryoliver** [comment]
@diegoribero awesome! :)
