### ISSUE TITLE
Installed Apps: stay blank

### ISSUE THREAD

**Issue by nebiljabari** [matrix-io/matrix-os#19]
With the new updates : `Matrix CLI 1.2.0` - `Matrix OS 0.5.5`
I tried several times to run the clock exemple unsuccessfully. Im always stuck in the same step. `Installed Apps :` stay blank causing a `Firebase Warning`

```
Installed Apps: 
Local Apps: [ 'clock.matrix' ]
Local / Installed Δ 1
FIREBASE WARNING: Exception was thrown by user callback. TypeError: _.pickBy is not a function
...several lines skipped...
```

When I `matrix list apps` I see the deployed app

```
 ┌───────────────────────────┬───────┬───────────────────────────────────────────────────────────────────────────────────┐
│ Name                      │ v     │ Description                                                                       │
│ clock                     │ 1.0.0 │                                                                                   │
└───────────────────────────┴───────┴───────────────────────────────────────────────────────────────────────────────────┘
```

I tried to rename the app and to redo the procedure allowing me to run it last week. No success

**Comment by eighteyes** [comment]
We had a lodash 3 hanging around. I believe it's in the `matrix-node-sdk` module. That module should be updated to the latest and run `npm dedupe` to resolve the different versions in your node modules.

**Comment by nebiljabari** [comment]
I followed your advice and now :

```
Installed Apps: 
Local Apps: [ 'clock1.matrix' ]
Local / Installed Δ 1
installing ac34c007157e
FIREBASE WARNING: Exception was thrown by user callback. TypeError: Matrix.service.firebase.deviceapps.get is not a function
...lines skipped...
```

```
pi@raspberrypi:~/matrix-os $ sudo matrix list apps
 ┌───────────────────────────┬───────┬────────────────────────────────────────────────────────────────────────────────────────┐
│ Name                      │ v     │ Description                                                                            │
│ clock1                    │ 1.0.0 │                                                                                        │
└───────────────────────────┴───────┴────────────────────────────────────────────────────────────────────────────────────────┘
```

ps: I use `sudo`because I can't deploy without (you create the `.zip` file in a protected area)

**Comment by eighteyes** [comment]
This has been addressed. We've got upgrades installed, so matrix and it's subcomponents should update automatically.

**Comment by eighteyes** [comment]
Please install 0.5.6 of matrix os

**Comment by eighteyes** [comment]
We're still working on uninstall. :) I don't think that removes cleanly.

**Comment by brianofrokk3r** [comment]
@diegoribero updates, i see some PRs for this, want to make sure we update this one.

**Comment by diegoribero** [comment]
OS 0.6.0 has been merged to master, this is now working :)
