### ISSUE TITLE
API Error:  400 - Missing deviceSecret parameter.

### ISSUE THREAD

**Issue by adrian2lee** [matrix-io/matrix-os#22]
after node index.js
> ....
> Dependencies up to date.
> Device Error { status: 'error',
>   status_code: 400,
>   error: 'Missing deviceSecret parameter.' }
> API Error:  400 - Missing deviceSecret parameter.

I have .envrc file in ~

> export MATRIX_DEVICE_ID=XZXZXZXZXZXZX
> export MATRIX_DEVICE_SECRET=ZXZXZXZXZXZXZXZXZXZXZXZXZXZXZX

source .envrc

**Comment by adrian2lee** [comment]
SOLVED by something

> git submodule update --init
> npm install
in matrix-os/ again and also made
source .envrc
again

**Comment by eighteyes** [comment]
Great! Closing! Darn submodules.

**Comment by adrian2lee** [comment]
I keep having to do source .envrc after reboot to bypass this error message, how can I fix this permanently?

**Comment by eighteyes** [comment]
`cat .envrc >> ~/.bash_profile` should load it on startup
