### ISSUE TITLE
Stopping an app that has already been stopped

### ISSUE THREAD

**Issue by manojkumardas7** [matrix-io/matrix-os#25]
So if we try to stop an app that probably is already stopped or does not exist, from the CLI,  Matrix-OS stops running and needs to be started again... That should not happen.

**Comment by brianofrokk3r** [comment]
@diegoribero I believe this is fixed, can you validate?

**Comment by diegoribero** [comment]
You are right @brianofrokk3r, 28336239c99ff88a99e6fa9388f37a86ff46e156 fixed it and it's already merged to master
