### ISSUE TITLE
Error Install CLI on Local machine

### ISSUE THREAD

**Issue by opogc** [matrix-io/matrix-os#49]
Hi guys! I am trying to install the CLI following your instructions but I am getting an error. (No found git)
Can you please help me.
Thanks
-----

npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:112:15)
npm WARN addRemoteGit  git+https://github.com/matrix-io/matrix-app-config-helper.git resetting remote /home/student/.npm/_git-remotes/git-https-github-com-matrix-io-matrix-app-config-helper-git-8c39b1a9 because of error: { Error: not found: git
npm WARN addRemoteGit     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
npm WARN addRemoteGit     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
npm WARN addRemoteGit     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:112:15) code: 'ENOGIT' }
npm ERR! git clone --template=/home/student/.npm/_git-remotes/_templates --mirror https://github.com/matrix-io/matrix-app-config-helper.git /home/student/.npm/_git-remotes/git-https-github-com-matrix-io-matrix-app-config-helper-git-8c39b1a9: undefined
npm ERR! git clone --template=/home/student/.npm/_git-remotes/_templates --mirror https://github.com/matrix-io/matrix-app-config-helper.git /home/student/.npm/_git-remotes/git-https-github-com-matrix-io-matrix-app-config-helper-git-8c39b1a9: undefined
npm ERR! Linux 3.19.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "matrix-cli" "-g"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/student/npm-debug.log

**Comment by eighteyes** [comment]
Did you do this step

```
curl https://raw.githubusercontent.com/matrix-io/matrix-creator-quickstart/master/install.sh | sh
```

That installs git first thing.

**Comment by eighteyes** [comment]
Interesting, yes, I suppose git is needed for the auto upgrade functionality. We just assumed most developers had git. 

You can use your package manager (apt-get install git) to install git, or wait until we can fix this bug.

**Comment by diegoribero** [comment]
Closing this since Git is already listed as a requirement in [MATRIX CLI Installation docs](https://matrix-io.github.io/matrix-documentation/CLI/installation/)
