### ISSUE TITLE
When you manually fill in the color array for `matrix.led()`, it does not allow you to rotate.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-os#51]
When you manually fill in the color array for `matrix.led()`, it does not allow you to rotate. Attempting to re-create the everloop.

**Comment by eighteyes** [comment]
Please provide example code?

**Comment by eighteyes** [comment]
@brianofrokk3r have you tried `matrix.led( ... ).rotate( n )` ?

**Comment by brianofrokk3r** [comment]
Tested with the following code, should be working. You can also install the app to your device `matrix install ledRotationTest`.

Example App
```
// Initial set of LEDs (1-35)
var leds = matrix.led([0, 0, 0, 0, 'yellow', 0,
0, 0, 0, 0, 0, 0, 0, 'yellow', 0, 0,
0, 0, 0, 0, 0, 0, 'yellow', 'yellow',
'yellow', 'yellow', 'yellow', 'yellow',
'yellow', 'yellow', 'yellow' ]);

// Rotating the Face
var i = 0;
setInterval(()=>{
  // Rotate method
  leds.rotate(i).render();
  i = i+20;
},100);
```
