### ISSUE TITLE
matrix.led().darken(50) is not currently an active API. Expected to be able to set LED intensity.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-os#54]
`matrix.led().darken(50)` is not currently an active API. Expected to be able to set LED intensity.

**Comment by eighteyes** [comment]
`darken` has serious performance issues. It should just be removed from the docs until we figure it out.

**Comment by brianofrokk3r** [comment]
@eighteyes removed from API until we adjust.
