### ISSUE TITLE
Duplicate trigger events received on CLI matrix trigger.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-os#6]
Duplicate trigger events received on CLI matrix trigger. Issue when running `matrix trigger foo`. Received duplicate trigger events on OS level.

**Comment by brianofrokk3r** [comment]
![screen shot 2016-09-27 at 3 13 27 pm](https://cloud.githubusercontent.com/assets/113014/18888128/0932e624-84c5-11e6-9927-ad1766e9f52a.png)

**Comment by brianofrokk3r** [comment]
@eighteyes

**Comment by eighteyes** [comment]
:( ok

**Comment by eighteyes** [comment]
Unable to reproduce @brianofrokk3r Please re-open if this shows up again.
