### ISSUE TITLE
Issue when toggling on and off apps that use Face Detection.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/matrix-os#65]
When toggling on/off apps that use face detection, seems that `malos_eye` is not getting reinitialized for subsequent uses of the same application. Therefore, no face detection events are fired after future uses.

**Comment by brianofrokk3r** [comment]
@eighteyes @diegoribero did we get to this?

**Comment by eighteyes** [comment]
Nope. It's probably an issue with all the services. I'll look at it this
week.

**Comment by brianofrokk3r** [comment]
@eighteyes
