### ISSUE TITLE
YAML config file

### ISSUE THREAD

**Issue by vjoao** [matrix-io/matrix-os#70]
Hello, this is just to raise some discussion =)

Is there any particular reason of choosing YAML as the main config entrypoint?
Why not an easier to parse and understand format like JSON?

**Comment by eighteyes** [comment]
YAML is easier for humans to parse then JSON, it takes a little learning, but we aren't asking for very complicated structures. Plus it won't go crazy if you add an extra comma or use single quotes.

We are striving to make our system as approachable as possible for novice developers, while retaining sufficient power and flexibility for advanced users.

**Comment by vjoao** [comment]
Point taken =)
