### ISSUE TITLE
HTS221 sensor reading wrong values for temperature

### ISSUE THREAD

**Issue by vjoao** [matrix-io/matrix-os#71]
Humidity seems to be OK but temperature readings always seem to be off. 
This might be caused by driver issues not being able to calibrate the sensor on startup.

Any thoughts?

**Comment by vjoao** [comment]
Moved to HAL

**Comment by vjoao** [comment]
Moved to MALOS

**Comment by brianofrokk3r** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sensor reading wrong values from Temperature](https://trello.com/c/W9lciHXw/3-sensor-reading-wrong-values-from-temperature)
