### ISSUE TITLE
Matrix OS: Error upgrading MOS API dependencies: Error: spawn /bin/sh ENOENT

### ISSUE THREAD

**Issue by delsner** [matrix-io/matrix-os#76]
Hi, 

I am getting the Error "Error upgrading MOS API dependencies: Error: spawn /bin/sh ENOENT" when starting up the matrix os. It worked until last night, just this morning it occured for the first time when I was starting up the matrix os. Do you know of any dependencies that have been updated last night that could have broke it?

Thanks in advance.

**Comment by eighteyes** [comment]
Try `npm run upgrade` from the `matrix-os` repo.
