### ISSUE TITLE
sources.list error

### ISSUE THREAD

**Issue by amoun00** [matrix-io/matrix-os#8]
Dear Matrix-io team,

I am having a problem while getting the sources.list 

E: malformed line 5 in source list / etc/apt/sources.list (absolute dist)
E: the list of sources could not be read.

Please help

Rabih

**Comment by brianofrokk3r** [comment]
Hey @amoun00, If you have a resolution pertinent to the documentation please drop it here! Otherwise, we're glad you fixed it!
