### ISSUE TITLE
Can't Find Open Source Software Licenses

### ISSUE THREAD

**Issue by massonpj** [matrix-io/matrix-os#91]
Looking at the Indiegogo campaign the project page states, "MATRIX Voice: Open-Source Voice Platform For All", "MATRIX Voice is an open-source VOICE RECOGNITION platform consisting of a 3.14-inches in diameter dev board, with a radial array of 7 MEMS microphones connected to a Xilinx Spartan6 FPGA & 64 Mbit SDRAM with 18 RGBW LED’s & 64 GPIO pins", "Open-Source Voice Platform for All", "Matrix Open-Source" etc. (https://www.indiegogo.com/projects/matrix-voice-open-source-voice-platform-for-all#/).

In addition, the [README.md](https://github.com/matrix-io/matrix-os/blob/master/README.md) states, "MATRIX Open Source is a platform for running applications on the MATRIX Creator", "Open Source: We built MATRIX on top of open source software and we are releasing it for everyone to see under the hood and make contributions:sunglasses:. We believe in open access to information, especially for the IoT space, where security and privacy are of the utmost importance."

Yet I cannot find an OSI Approved Open Source Licenses in any of the project repositories. Can you please point me to it.

Thanks,
Patrick

**Comment by diegoribero** [comment]
Hey Patrick

Thank you for pointing this out, the LICENSE files have now been included.
